"""
Router - Main orchestration module for the multi-agent AI system.

Architecture:
User Query → ClassifierAgent → PlannerAgent (optional) → Selected Agent → Tools → VerifierAgent → Response → MemoryAgent
"""

from agents.ChatAgent import chat
from agents.ClassifierAgent import ClassifierAgent
from agents.CodingAgent import coding
from agents.ImageAgent import image
from agents.LogicalAgent import logical
from agents.MemoryAgent import process_memory
from agents.PlannerAgent import planner, extract_json as extract_plan
from agents.VerifierAgent import verify
from agents.VisionAgent import vision

from tools.Memory import get_context_for_query

import json


def execute_plan(query: str, plan: dict, agent_type: str) -> str:
    """
    Execute a plan generated by PlannerAgent.
    
    Args:
        query: Original user query
        plan: The execution plan from PlannerAgent
        agent_type: Type of agent to use for execution
    
    Returns:
        Final response after executing all steps
    """
    results = []
    
    for step in plan.get("steps", []):
        step_query = f"Step {step['step']}: {step['title']} - {step['description']}"
        
        if agent_type == "coding":
            result = coding(step_query)
        elif agent_type == "logical":
            result = logical(step_query)
        elif agent_type == "chat":
            result = chat(step_query)
        else:
            result = chat(step_query)
        
        results.append(f"Step {step['step']} completed: {result[:200]}...")
    
    return "\n\n".join(results)


def route_and_execute(QUERY: str, context: dict = None):
    """
    Main routing function that orchestrates the entire agent system.
    
    Args:
        QUERY: User's query
        context: Optional context including conversation history, memory, etc.
    
    Returns:
        Final response to the user
    """
    # Step 1: Classify the request
    route = ClassifierAgent(QUERY)
    
    agent_type = route.get("agent", "chat")
    planning_required = route.get("planning_required", False)
    memory_required = route.get("memory_required", False)
    verification_required = route.get("verification_required", False)
    
    # Step 2: Retrieve memory if needed
    memory_context = ""
    if memory_required:
        memory_context = get_context_for_query(QUERY)
        if memory_context and memory_context != "No relevant memory found.":
            QUERY = f"{QUERY}\n\nRelevant memory:\n{memory_context}"
    
    # Step 3: Plan if required
    plan = None
    if planning_required:
        plan_raw = planner(QUERY)
        try:
            plan = extract_plan(plan_raw)
        except:
            plan = None
    
    # Step 4: Execute with selected agent
    if plan:
        response = execute_plan(QUERY, plan, agent_type)
    elif agent_type == "chat":
        response = chat(QUERY)
    elif agent_type == "coding":
        response = coding(QUERY, context=context)
    elif agent_type == "logical":
        response = logical(QUERY)
    elif agent_type == "vision":
        # Vision requires image data - would need to be passed in context
        response = vision(QUERY, image_data=context.get("image") if context else None)
    elif agent_type == "image":
        response_dict = image(QUERY)
        response = json.dumps(response_dict, indent=2)
    else:
        response = chat(QUERY)
    
    # Step 5: Verify if required
    if verification_required:
        verification = verify(response, QUERY, agent_type)
        if not verification.get("approved", True):
            # Request revision - in production, would loop back to agent
            issues = verification.get("issues", [])
            if issues:
                response += f"\n\n[Verification notes: {', '.join(issues)}]"
    
    # Step 6: Update memory (async in production)
    # For now, process memory synchronously
    try:
        process_memory(QUERY, response)
    except Exception as e:
        pass  # Don't fail if memory update fails
    
    return response


def router(QUERY):
    """Simple router function for backward compatibility."""
    route = ClassifierAgent(QUERY)
    return route


if __name__ == "__main__":
    print("=" * 60)
    print("Local AI Agent System - Router Test")
    print("=" * 60)
    
    test_queries = [
        # Chat
        "Why do airplanes leave white trails in the sky?",
        "Explain blockchain like I'm 12 years old.",
        
        # Logical
        "I have $5,000 to invest. Compare index funds, bonds, and gold for a 10-year horizon.",
        "Analyze the pros and cons of remote work versus office work.",
        
        # Coding
        "Create a FastAPI service with JWT authentication.",
        
        # Image Generation
        "Create a futuristic cyberpunk city skyline at sunset.",
        
        # Ambiguous (should trigger memory)
        "Continue.",
    ]
    
    for i, query in enumerate(test_queries, 1):
        print(f"\n{'='*60}")
        print(f"Query {i}: {query}")
        print(f"{'='*60}")
        
        # Show classification
        route = ClassifierAgent(query)
        print(f"\nClassification:")
        print(json.dumps(route, indent=2))
        
        # Uncomment below to test full execution (requires Ollama running)
        # response = route_and_execute(query)
        # print(f"\nResponse:\n{response[:500]}...")
